version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/node_api?schema=public
      - JWT_SECRET=your-super-secret-key-here
      - PORT=3000

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=node_api
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: